// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CircleChatroomSubscriptionController from "./circle_chatroom_subscription_controller"
application.register("circle-chatroom-subscription", CircleChatroomSubscriptionController)

import FlatpickerController from "./flatpicker_controller"
application.register("flatpicker", FlatpickerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import GradientController from "./gradient_controller"
application.register("gradient", GradientController)

